# syntax=docker/dockerfile:1
#
# Production image for Finalysis.
#
# Three stages, and the third one contains almost nothing:
#
#   deps     full dependency tree, installed exactly as the lockfile records it
#   builder  compiles the app and emits Next's standalone server
#   runner   the standalone server, plus the static assets it needs at runtime
#
# The runner never sees a compiler, a package manager, a lockfile, a test or a
# source file. That is the point of `output: "standalone"` in next.config.ts:
# it copies the server across with only the modules that are actually imported,
# traced through the build rather than guessed at.

ARG NODE_VERSION=22
ARG PNPM_VERSION=10.28.1

# ---------------------------------------------------------------------------
# deps: the whole tree, because the build needs the dev dependencies too.
# ---------------------------------------------------------------------------
FROM node:${NODE_VERSION}-alpine AS deps
ARG PNPM_VERSION
WORKDIR /app

# Corepack reads the version from package.json#packageManager, so the declared
# version and the installed version cannot drift apart.
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate

# Copied on their own so this layer is cached until a dependency actually
# changes, which is most of the reason a build does not start from nothing.
COPY package.json pnpm-lock.yaml .npmrc* ./
RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    pnpm config set store-dir /pnpm/store && \
    pnpm install --frozen-lockfile

# ---------------------------------------------------------------------------
# builder: compile, then emit the self-contained server.
# ---------------------------------------------------------------------------
FROM node:${NODE_VERSION}-alpine AS builder
ARG PNPM_VERSION
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# NEXT_PUBLIC_* values are inlined into the client bundle at build time, so this
# is the only moment the site URL can be set. Nothing secret goes here; there is
# no secret that belongs in a bundle, and anything set here would be readable by
# anyone who loaded the page.
ARG NEXT_PUBLIC_SITE_URL=https://finalysis.vercel.app
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}

RUN pnpm run build

# ---------------------------------------------------------------------------
# runner: the server and nothing else.
# ---------------------------------------------------------------------------
FROM node:${NODE_VERSION}-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# The official image already ships an unprivileged `node` user, so no user is
# invented here and no uid has to be kept in step across builds.
COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static
# There is deliberately no COPY for /app/public, because this repository has no
# public/ directory and a COPY of a missing path fails the build. Every asset is
# either an app route (/icon.svg, /robots.txt, /sitemap.xml are generated by
# Next) or a font committed under app/fonts and inlined by next/font/local.
# If a public/ directory is added later, copy it here.

USER node

EXPOSE 3000

# The liveness endpoint. It answers from the process alone and deliberately
# calls nothing external, so a slow third party cannot make Docker restart a
# healthy container.
HEALTHCHECK --interval=30s --timeout=3s --start-period=15s --retries=3 \
    CMD node -e "fetch('http://127.0.0.1:3000/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

# Next's standalone server installs its own SIGTERM/SIGINT handling and drains
# in-flight requests, which is what makes `kubectl delete pod` and a rolling
# update cut over without 502s. CMD is exec-form so node is PID 1 and receives
# the signal directly rather than through a shell.
CMD ["node", "server.js"]